version: '3.7'
services:
  # MySql Service
  database:
    image: mysql:8.0.20
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: pcbee-db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: local
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # # PHP Service
  # backend:
  #   build: .
  #   restart: unless-stopped
  #   tty: true
  #   working_dir: /var/www/
  #   ports:
  #     - '9001:9000'
  #   volumes:
  #     - '.:/var/www'
  #     - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/upload.ini
  #   networks:
  #     - app-network

  # # Webserver Service
  # webserver:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - '81:80'
  #     - '443:443'
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local