version: '3.7'
services:
  # MySql Service
  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: pcbee-db
      # MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  # PHP Service
  app:
    container_name: app
    build: 
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - '9000:9000'
    volumes:
      - './api:/var/www/html'
      # - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/upload.ini
    networks:
      - app-network

  # Webserver Service
  server:
    image: nginx:stable-alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - '8000:80'
     # - '8443:443'
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local